components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-20.2.3
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: a2202c45a65c2dd879c6a8f6f3b759aa4b37da6e
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: 9f578fe5d8307c11b0fe39eb500899fe505c666f
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 0486eb0eb572f7a9e19f38f2daad65fafd7ffc2c
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 18a7db778c3ec50265d3d88810f93892e18fbb2a
    type: git
  level_zero:
    branch: master
    dest_dir: level_zero
    repository: https://github.com/oneapi-src/level-zero
    revision: v1.0
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: a5f71b6696eb7679ebb263ee226e34520397ed00-1451
converter: M-1451
version: '1'
