components:
  gmmlib:
    dest_dir: gmmlib
    type: git
    branch: gmmlib
    revision: intel-gmmlib-20.2.3
    repository: https://github.com/intel/gmmlib.git
  igc:
    dest_dir: igc
    type: git
    branch: igc
    revision: fa441b4bcb30aa949b17f644157a5d0c20b07b3c
    repository: https://github.com/intel/intelgraphicscompiler
  infra:
    branch: infra
    dest_dir: infra
    revision: 0a6a620bba78c7978cc82d96c6f9f7b78575faac
    type: git
  internal:
    branch: master
    dest_dir: internal
    revision: 02468f7b07815e93b0717383c450b5bf1c147548
    type: git
  kmdaf:
    branch: kmdaf
    dest_dir: kmdaf
    revision: 57e0a77511edfc4ca0e42b939075d1ab23c48a09
    type: git
  level_zero:
    branch: master
    dest_dir: level_zero
    repository: https://github.com/oneapi-src/level-zero
    revision: v1.0
    type: git
  libva:
    dest_dir: libva
    type: git
    branch: libva
    revision: c9bb65b
    repository: https://github.com/intel/libva.git
  wdk:
    dest_dir: wdk
    type: git
    branch: wdk
    revision: 89abb3e1e441fd57c80680f62c9aa4e3ecaf9ac7-1443
converter: M-1444
version: '1'
